import type { NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const QuestionsView = () => {
  const { data, isLoading } = trpc.useQuery(["questions.get-my-question"]);

  const { mutate: pinQuestion } = trpc.useMutation(["questions.pin-question"]);

  return (
    <div className="flex flex-col">
      {data?.map((q) => (
        <div key={q.id}>
          {q.body}
          <button onClick={() => pinQuestion({ questionId: q.id })}>Pin</button>
        </div>
      ))}
    </div>
  );
};

const HomeContents = () => {
  const { data, status } = useSession();

  if (status === "loading") return <div>Loading...</div>;

  if (!data) {
    return (
      <div>
        <div>Please log in</div>
        <button onClick={() => signIn("twitch")}>Sign in with Twitch</button>
      </div>
    );
  }

  return (
    <div className="flex flex-col">
      Hello {data.user?.name} {data.user?.id}
      <QuestionsView />
    </div>
  );
};

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Twitch Ask Chat</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeContents />
    </>
  );
};

export default Home;
