import type { NextPage } from 'next';
import { signIn, signOut, useSession } from 'next-auth/react';
import Head from 'next/head';
import { trpc } from '../utils/trpc';

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const HomeContents = () => {
  const { data, status } = useSession();

  if (status === 'loading') return <div>Loading...</div>;

  if (!data) {
    return (
      <div>
        <div>Please log in</div>
        <button onClick={() => signIn('twitch')}>Sign in with Twitch</button>
      </div>
    );
  }

  return (
    <div>
      Hello {data.user?.name}
      <button onClick={() => signOut()}>Sign out</button>
    </div>
  );
};

const Home: NextPage = () => {
  const hello = trpc.useQuery(['example.hello', { text: 'from tRPC' }]);

  return (
    <>
      <Head>
        <title>Twitch Ask Chat</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeContents />
    </>
  );
};

export default Home;
